name: Development PR Review

on:
  pull_request_target:
    branches: [development]
  pull_request_review:


jobs:
  check-reviewers-development:
    if: github.event.pull_request.base.ref == 'development'
    runs-on: ubuntu-latest

    steps:
      - name: Required Review
        uses: Automattic/action-required-review@v3.0.1
        with:
          requirements: |
            - name: Others
              paths: unmatched
              teams:
                - maintainers
          status: Review Required
          fail: true
          token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}
  # debug:
  #   runs-on: ubuntu-latest

  #   steps:
  #   - name: Debug
  #     run: |
  #       echo "github.event.pull_request.base.ref=${{ github.event.pull_request.base.ref }}"
  #       echo "matches branch=${{ github.event.pull_request.base.ref == 'development' }}"
