name: Pull Request Reviewers

on:
  pull_request:
    branches:
      - main
  pull_request_target:
    branches:
      - main
  pull_request_review:


jobs:
  check-reviewers:
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Required Review
        uses: Automattic/action-required-review@v2.2.2
        with:
          requirements-file: .github/reviewers/branch-main.yaml
          status: Review Required
          # fail: true
          token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}
