name: Pull Request Reviewers

on:
  pull_request_target:
    branches:
      - '**-prototype-**'
  pull_request_review:


jobs:
  check-reviewers:
    if: contains(github.event.pull_request.base.ref, '-prototype-')
    runs-on: ubuntu-latest

    steps:
      - name: PR Required Reviewers
        uses: Automattic/action-required-review
        with:
          requirements-file: .github/reviewers/branch-prototype.yaml
          status: Review Required
          fail: true
          token: ${{ secrets.INTERSECTBOT_ACCESS_TOKEN }}